// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import path from "path";
import { defineConfig, env } from "prisma/config";

dotenv.config({
    path: path.resolve(__dirname, "../../.env"),
});
const databaseUrl = process.env.DATABASE_URL;
console.log(databaseUrl);
export default defineConfig({
    schema: "./schema.prisma",
    migrations: {
        path: "./migrations",
        seed: "tsx ./seed.ts",
    },
    datasource: {
        url: databaseUrl,
    },
});
